### ISSUE TITLE
additional constraints to reduce symmetry not working correctly

### ISSUE THREAD

**Issue by ostasis** [ostasis/One-dimensional#1]
Hi,
I need help.  Please download  [Lachster.csv](https://github.com/ostasis/One-dimensional/blob/master/Lachster.csv) and try it with my app. [![Binder](https://mybinder.org/badge.svg)](https://mybinder.org/v2/gh/ostasis/One-dimensional/master?urlpath=%2Fapps%2Fone-dimensional-bin-packing.ipynb).  I'm getting different results with the widget checkbox "Reduce symmetry".  Unchecked the result is correct, but checked it is adding extra cut lengths.  For example "Lachster.csv" has 9 @ 2000 but the result shows a total of 11 @ 2000.
`    if checkbox1.value == True:
        for j in range(1, n):
            model.add_constr(y[j - 1] >= y[j])`
Thanks.

**Comment by h-g-s** [comment]
Hi, could you provide the .csv and a .py file to run separately and debug the issue ?

**Comment by ostasis** [comment]
Hi, thanks for your help. Python file is [here](https://github.com/ostasis/One-dimensional/blob/master/from-docs-python-mip-com.py).  This represent variables `n, L, m, w, b` as they would be in the notebook referred to above using Lachster.csv.  (Also added a notebook with less widgets etc.  Run the first cell > upload Lachster.csv file > Run all cells below.  You will need to have a "files" folder at the same level as the notebook).  Thanks.
```
n = 8  # maximum number of bars
L = 6000  # bar length
m = 7  # number of requests
w = [456, 2000, 888, 758, 600, 423, 300]
b = [5, 9, 7, 12, 5, 3, 8]
```
Returns 11 @ 2000 (see below in bold):
Objective value: 8.0
Solution: x[0,0] = 1.0
          x[0,6] = 4.0
          **x[1,1] = 3.0
          x[1,3] = 3.0
          x[1,5] = 3.0
          x[1,6] = 2.0**
          x[2,4] = 6.0
          x[2,7] = 1.0
          x[3,2] = 7.0
          x[3,7] = 5.0
          x[4,0] = 5.0
          x[4,2] = 1.0
          x[4,4] = 1.0
          x[5,7] = 3.0
          x[6,0] = 8.0
          y[0] = 1.0
          y[1] = 1.0
          y[2] = 1.0
          y[3] = 1.0
          y[4] = 1.0
          y[5] = 1.0
          y[6] = 1.0
          y[7] = 1.0

**Comment by h-g-s** [comment]
Could you try to replace

# constraints
for i in range(m):
    model.add_constr(xsum(x[i, j] for j in range(n)) >= b[i])

for 

# constraints
for i in range(m):
    model.add_constr(xsum(x[i, j] for j in range(n)) == b[i])

 ?

**Comment by ostasis** [comment]
Thank you, this has resolved the issue.  Much appreciated.
